bank/bank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls')),
    path('bank/',include('bankapp2.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bank/bankapp/urls.py
from . import views
from django.urls import path
app_name='bankapp'
urlpatterns = [
    path('',views.Home,name='Home'),

]

bank/bankapp2/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('add/', views.data_create_view, name='person_add'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

]

bank/bankapp/models.py
from django.db import models

# Create your models here.
class MainDetails(models.Model):
    img=models.ImageField(upload_to='mainimage')
    heading=models.CharField(max_length=250)
    desc=models.TextField(default=True)

    def __str__(self):
        return self.heading

class Faclities(models.Model):
    img=models.ImageField(upload_to='faclities')
    name=models.CharField(max_length=250)
    desc=models.TextField()

    def __str__(self):
        return self.name

bank/bankapp2/models.py
from django.db import models

# Create your models here.
class District(models.Model):
    name=models.CharField(max_length=250)

    def __str__(self):
        return self.name

class Branch(models.Model):
    district=models.ForeignKey(District,on_delete=models.CASCADE)
    name=models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Data(models.Model):
    name=models.CharField(max_length=300)
    dob=models.TextField(default=True)
    age=models.IntegerField(default=True)
    gender=models.TextField(default=True)
    phone=models.IntegerField(default=True)
    mail=models.EmailField(default=True)
    address=models.TextField(default=True)
    district=models.ForeignKey(District,on_delete=models.CASCADE,default=True)
    branch=models.ForeignKey(Branch,on_delete=models.CASCADE,default=True)
    account=models.TextField(default=True)
    material=models.TextField(default=True)

    def __str__(self):
        return self.name

bank/bankapp2/forms.py
from django import forms
from .models import Data, Branch


class DataCreationForm(forms.ModelForm):
    class Meta:
        model = Data
        fields = ['district','branch']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch'].queryset = Branch.objects.none()

        if 'district' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['branch'].queryset = Branch.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['branch'].queryset = self.instance.district.branch_set.order_by('name')

bank/bankapp/views.py
from django.shortcuts import render
from .models import MainDetails,Faclities

# Create your views here.
def Home(request):
    obj=MainDetails.objects.all()
    obb=Faclities.objects.all()
    return render(request,'index.html',{'obj':obj,'obb':obb})

bank/bankapp2/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import Data,Branch
from .forms import DataCreationForm


# Create your views here.
def register(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        cpassword=request.POST['cpassword']

        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,'Username already exist')
                return redirect('register')

            else:
                user = User.objects.create_user(username=username, password=password)
                user.save();

                return redirect('login')
        else:
            messages.info(request,'Password is not matching')
            return redirect('register')

    return render(request,'register.html')

def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']

        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('person_add')

        else:
            messages.info(request,'Incorrect entry')
            return redirect('login')


    return render(request,'login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

def data_create_view(request):
    form = DataCreationForm()
    if request.method == 'POST':
        name = request.POST['name']
        dob = request.POST['dob']
        age = request.POST['age']
        gender = request.POST['gender']
        phone = request.POST['phone']
        mail = request.POST['mail']
        address = request.POST['address']
        account = request.POST['account']
        material = request.POST.getlist('material')

        data=Data(name=name,dob=dob,age=age,gender=gender,phone=phone,mail=mail,address=address,account=account,material=material)
        data.save()

        messages.info(request,'Application Accepted')

        form = DataCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('person_add')
    return render(request, 'login_page.html', {'form': form})


# AJAX
def load_cities(request):
    district_id = request.GET.get('district_id')
    branches = Branch.objects.filter(district_id=district_id).all()
    return render(request, 'abc.html', {'branches': branches})

bank/templates/abc.html
<option value="">---------</option>
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}

bank/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;700;900&display=swap" rel="stylesheet">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/slick.css' %}"/>

    <link href="{% static 'css/tooplate-little-fashion.css' %}" rel="stylesheet">

    <script src="https://kit.fontawesome.com/1b99dd44bf.js" crossorigin="anonymous"></script>

    <title>Title</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

bank/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">

        <title>Marvel Bank</title>

        <!-- CSS FILES -->
        <link rel="preconnect" href="https://fonts.googleapis.com">

        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;700;900&display=swap" rel="stylesheet">

        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/slick.css' %}"/>

        <link href="{% static 'css/tooplate-little-fashion.css' %}" rel="stylesheet">

        <script src="https://kit.fontawesome.com/1b99dd44bf.js" crossorigin="anonymous"></script>

<!--

Tooplate 2127 Little Fashion

https://www.tooplate.com/view/2127-little-fashion

-->
    </head>
    
    <body>

        <section class="preloader">
            <div class="spinner">
                <span class="sk-inner-circle"></span>
            </div>
        </section>
    
        <main>

            <nav class="navbar navbar-expand-lg">
                <div class="container">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <a class="navbar-brand" href="{% url 'bankapp:Home' %}">
                        <strong><span>Marvel</span> Bank</strong>
                    </a>

                    <div class="d-lg-none">
                        <a href="sign-in.html" class="bi-person custom-icon me-3"></a>

                        <a href="product-detail.html" class="bi-bag custom-icon"></a>
                    </div>

                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'bankapp:Home' %}"><i class="fa-solid fa-house-user"></i> Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}">Login</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'register' %}">Register</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Branches
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a></li>
                                    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
                                    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Trissur">Trissur</a></li>
                                    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a></li>
                                    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Thiruvananthapuram</a></li>

                                </ul>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="#">FAQs</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="#">Contact</a>
                            </li>
                        </ul>

                    </div>
                </div>
            </nav>

            {% for i in obj %}
            <section>
                <div class="slick-custom">
                    <img src="{{i.img.url}}" class="img-fluid" alt="">

                    <div class="slick-bottom">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-6 col-10">
                                    <h1 class="slick-title">{{i.heading}}</h1>

                                    <p class="lead text-white mt-lg-3 mb-lg-5">{{i.desc}}</p>

                                    <a href="#" class="btn custom-btn">Join with us</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {% endfor %}



            <section class="about section-padding">
                <div class="container">
                    <div class="row">

                        <div class="col-12 text-center">
                            <h2 class="mb-5">Get started with <span>Marvel</span> Bank</h2>
                        </div>
                    </div>
                </div>
            </section>

            <section class="front-product">
                <div class="container-fluid p-0">
                    <div class="row align-items-center">

                        <div class="col-lg-6 col-12">
                            <img src="{% static 'images/bank1.jpg' %}" class="img-fluid" alt="">
                        </div>

                        <div class="col-lg-6 col-12">
                            <div class="px-5 py-5 py-lg-0">
                                
                                <h2 class="mb-4"><span>Marvel</span> Bank</h2>

                                <p class="lead mb-4">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.</p>

                                <a href="#" class="custom-link">
                                    Explore Banking
                                    <i class="bi-arrow-right ms-2"></i>
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
            </section>

            <section class="featured-product section-padding">
                <div class="container">
                    <div class="row">
                        
                        <div class="col-12 text-center">
                            <h2 class="mb-5">Our Featured Facilities</h2>
                        </div>
                        {% for i in obb %}
                        <div class="col-lg-4 col-12 mb-3">
                            <div class="card p-3 shadow" style="width: 20rem;">
                                <img src="{{i.img.url}}" height="200px" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">{{i.name}}</h5>
                                    <p class="card-text">{{i.desc}}.</p>
                                    <a href="#" class="btn btn-primary">View Details</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </section>

        </main>

        <footer class="site-footer">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-10 me-auto mb-4">
                        <h4 class="text-white mb-3"><a href="index.html">Marvel</a> Bank</h4>
                        <p class="copyright-text text-muted mt-lg-5 mb-4 mb-lg-0">Copyright © 2023 <strong>Marvel Bank</strong></p>
                        <br>
                        <p class="copyright-text">Designed by <a href="#" target="_blank">-JB-</a></p>
                    </div>

                    <div class="col-lg-5 col-8">
                        <h5 class="text-white mb-3">Sitemap</h5>

                        <ul class="footer-menu d-flex flex-wrap">
                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Branches</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Privacy policy</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">FAQs</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Contact</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-4">
                        <h5 class="text-white mb-3">Social</h5>

                        <ul class="social-icon">

                            <li><a href="#" class="social-icon-link bi-youtube"></a></li>

                            <li><a href="#" class="social-icon-link bi-whatsapp"></a></li>

                            <li><a href="#" class="social-icon-link bi-instagram"></a></li>

                            <li><a href="#" class="social-icon-link bi-skype"></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </footer>

        <!-- JAVASCRIPT FILES -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/Headroom.js' %}"></script>
        <script src="{% static 'js/jQuery.headroom.js' %}"></script>
        <script src="{% static 'js/slick.min.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>

    </body>
</html>

bank/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="container form">
    <div class="col-md-6">
        <h2>
            <a class="head" href="{% url 'bankapp:Home' %}">
                        <strong><span>Marvel</span> Bank</strong>
            </a>
        </h2>
         <div class="container">
            <img src="{% static 'images/logo.png' %}" class="img" alt="logoimg">
        </div>
    </div>
    <div class="col-md-6 p-3 shadow">
        <h2 class="head">login</h2>
        <form action="login" method="post" class="form">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="username" class="form-control" placeholder="Username">
            </div>
            <div class="form-group">
                <input type="password" name="password" class="form-control" placeholder="Password">
            </div>
            <div class="form-group">
                <input type="submit">
            </div>
            <div class="form-group">
                <a class="" href="{% url 'register' %}">Register</a>
            </div>

        </form>
        {% for msg in messages %}
            <h6><strong>{{msg}}</strong></h6>
        {% endfor %}
    </div>
</div>

{% endblock %}

bank/templates/login_page.html
{% extends 'base.html' %}
{% block body %}
<nav class="navbar navbar-expand-lg">
                <div class="container">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <a class="navbar-brand" href="{% url 'bankapp:Home' %}">
                        <strong><span>Marvel</span> Bank</strong>
                    </a>

                    <div class="d-lg-none">
                        <a href="sign-in.html" class="bi-person custom-icon me-3"></a>

                        <a href="product-detail.html" class="bi-bag custom-icon"></a>
                    </div>

                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item">

                            </li>
                        </ul>

                    </div>
                </div>
            </nav>

    <div class="container form">
        <div class="container p-3 shadow">
            <h2 class="head">registration form</h2>
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <form method="post" id="personForm" data-branches-url="{% url 'ajax_load_cities' %}" class="frm">
                    {% csrf_token %}
                    <div class="form-group shadow">
                        <input type="text" name="name" class="form-control" placeholder="Enter Name">
                    </div>
                    <div class="form-group shadow">
                        <input type="date" name="dob" class="form-control" placeholder="Date of Birth">
                    </div>
                    <div class="form-group shadow">
                        <input type="text" name="age" class="form-control" placeholder="Enter Age">
                    </div>
                    <div class="form-check">
                        <label>Select Your Gender</label><br>
                        <input type="radio" name="gender" class="form-check-input" value="male"><label class="form-check-label">Male</label><br>
                        <input type="radio" name="gender" class="form-check-input" value="female"><label class="form-check-label">female</label><br>
                    </div>
                    <div class="form-group shadow">
                        <input type="text" name="phone" class="form-control" placeholder="Enter Phone Number">
                    </div>
                    <div class="form-group shadow">
                        <input type="email" name="mail" class="form-control" placeholder="Enter E-Mail">
                    </div>
                    <div class="form-group shadow">
                        <input type="text" name="address" class="form-control" placeholder="Enter Address">
                    </div>
                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
                    <div class="form-group shadow">
                        <select class="form-select p-3 shadow" name="account">
                            <option selected>Open this select menu</option>
                            <option value="savings">savings</option>
                            <option value="current">current</option>
                        </select>
                    </div>
                    <div class="form-check">
                        <label>Materials Available</label><br>
                        <input type="checkbox" name="material" class="form-check-input" value="Debitcard"><label class="form-check-label">Debitcard</label><br>
                        <input type="checkbox" name="material" class="form-check-input" value="Creditcard"><label class="form-check-label">Creditcard</label><br>
                        <input type="checkbox" name="material" class="form-check-input" value="Cheque"><label class="form-check-label">Cheque</label><br>
                        <input type="submit" class="btn btn-success">&nbsp; <a href="{% url 'logout' %}" class="btn btn-secondary">Logout</a>
                    </div>

                </form>

                {% for i in messages %}
                <h6><strong>{{i}}</strong></h6>
                {% endfor %}

                <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script>
                    $("#id_district").change(function () {
                        const url = $("#personForm").attr("data-branches-url");  // get the url of the `load_cities` view
                        const districtId = $(this).val();  // get the selected country ID from the HTML input

                        $.ajax({                       // initialize an AJAX request
                            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                            data: {
                                'district_id': districtId       // add the country id to the GET parameters
                            },
                            success: function (data) {   // `data` is the return of the `load_cities` view function
                                $("#id_branch").html(data);  // replace the contents of the city input with the data that came from the server
                                /*

                                let html_data = '<option value="">---------</option>';
                                data.forEach(function (branch) {
                                    html_data += `<option value="${branch.id}">${branch.name}</option>`
                                });
                                console.log(html_data);
                                $("#id_branch").html(html_data);

                                */
                            }
                        });

                    });
                </script>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
<footer class="site-footer">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-10 me-auto mb-4">
                        <h4 class="text-white mb-3"><a href="index.html">Marvel</a> Bank</h4>
                        <p class="copyright-text text-muted mt-lg-5 mb-4 mb-lg-0">Copyright © 2023 <strong>Marvel Bank</strong></p>
                        <br>
                        <p class="copyright-text">Designed by <a href="#" target="_blank">-JB-</a></p>
                    </div>

                    <div class="col-lg-5 col-8">
                        <h5 class="text-white mb-3">Sitemap</h5>

                        <ul class="footer-menu d-flex flex-wrap">
                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Branches</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Privacy policy</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">FAQs</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Contact</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-4">
                        <h5 class="text-white mb-3">Social</h5>

                        <ul class="social-icon">

                            <li><a href="#" class="social-icon-link bi-youtube"></a></li>

                            <li><a href="#" class="social-icon-link bi-whatsapp"></a></li>

                            <li><a href="#" class="social-icon-link bi-instagram"></a></li>

                            <li><a href="#" class="social-icon-link bi-skype"></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </footer>
{% endblock %}

bank/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="container form">
    <div class="col-md-6">
        <h2>
            <a class="head" href="{% url 'bankapp:Home' %}">
                        <strong><span>Marvel</span> Bank</strong>
            </a>
        </h2>
        <div class="container">
            <img src="{% static 'images/logo.png' %}" class="img" alt="logoimg">
        </div>
    </div>
    <div class="col-md-6 p-3 shadow">
        <h2 class="head">Register</h2>
        <form action="register" method="post" class="form">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="username" class="form-control" placeholder="Enter Username">
            </div>
            <div class="form-group">
                <input type="password" name="password" class="form-control" placeholder="Enter password">
            </div>
            <div class="form-group">
                <input type="password" name="cpassword" class="form-control" placeholder="Confirm password">
            </div>
            <div class="form-group">
                <input type="submit">
            </div>
        </form>
        {% for msg in messages %}
        <h6><strong>{{msg}}</strong></h6>
        {% endfor %}
    </div>
    <div class="col-md-4"></div>
</div>

{% endblock %}